# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieSearchingAssigment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieSearchingAssigment
  pod 'Alamofire', '~> 4.8.2'
  pod 'AlamofireObjectMapper', '~> 5.2.0'

end
